In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [4]:
df = pd.read_csv("data/paris2024-athletes.csv", sep = ';')
df.head()

,nom,Lien vers la source,Discipline,Date de naissance,Pays,Âge,Fonction,Taille (en cm),Genre,Site de compétition,Latitude,Longitude,Nombre de compétitions,Date de début,Date de fin,Jours de compétitions,Médailles d'or,Médailles d'argent,Médailles de bronze,Record
0,"""671""",https://olympics.com/fr/paris-2024/athlete/-67...,Breaking,19/10/05,République populaire de Chine,18,Athlète,NaN,Femme,La Concorde 1,48.866406,2.321195,6,09/08/24,09/08/24,1,0,0,1,non
1,AABERG IVERSEN Sarah,https://olympics.com/fr/paris-2024/athlete/sar...,Handball,10/04/90,Danemark,34,Athlète,177.0,Femme,multisite,NaN,NaN,8,25/07/24,10/08/24,8,0,0,1,non
2,AARDAHL Maren,https://olympics.com/fr/paris-2024/athlete/mar...,Handball,02/03/94,Norvège,30,Athlète,183.0,Femme,multisite,NaN,NaN,8,25/07/24,10/08/24,8,1,0,0,non
3,AARONSON Paxten,https://olympics.com/fr/paris-2024/athlete/pax...,Football,26/08/03,États-Unis d'Amérique,21,Athlète,175.0,Homme,multisite,NaN,NaN,4,24/07/24,02/08/24,4,0,0,0,non
4,AARTS Laura,https://olympics.com/fr/paris-2024/athlete/lau...,Water-polo,10/08/96,Pays-Bas,28,Athlète,175.0,Femme,multisite,NaN,NaN,7,27/07/24,10/08/24,7,0,0,1,non

In [5]:
unique_values_list = df['Pays'].unique().tolist()   
print(unique_values_list)

['République populaire de Chine', 'Danemark', 'Norvège', "États-Unis d'Amérique", 'Pays-Bas', 'Suède', 'Kazakhstan', 'Espagne', 'Israël', 'Italie', 'Qatar', 'Albanie', 'Chili', 'Équipe olympique des réfugiés', 'Türkiye', 'Égypte', 'République arabe syrienne', 'Serbie', 'Soudan', 'Maroc', 'Belgique', 'Ouzbékistan', "République islamique d'Iran", 'Singapour', 'Maldives', 'Azerbaïdjan', 'Canada', 'Ukraine', 'Tadjikistan', 'Japon', 'Sri Lanka', 'Inde', 'Autriche', 'Slovénie', 'Nigéria', 'Jordanie', 'France', 'Hongrie', 'Suisse', 'Allemagne', 'Guyana', 'Brésil', 'Libye', 'Kenya', 'Palestine', 'Arabie saoudite', 'Cuba', 'Guinée', 'Guinée équatoriale', 'Roumanie', 'Grèce', 'Australie', 'Bahreïn', 'Irlande', 'Indonésie', 'Togo', 'Lituanie', 'Algérie', 'Samoa', 'Porto Rico', 'Portugal', 'Mexique', 'Colombie', 'Pérou', 'Mauritanie', 'Niger', 'Iraq', "Côte d'Ivoire", 'Finlande', 'Trinité-et-Tobago', 'Kirghizistan', 'Oman', 'Émirats arabes unis', 'Yémen', 'Koweït', 'Pologne', 'Argentine', 'Angola', 'Grande-Bretagne', 'Venezuela', 'République dominicaine', 'Nouvelle-Zélande', 'Arménie', 'Éthiopie', 'AIN', 'Sainte-Lucie', 'Bermudes', 'Saint-Kitts-et-Nevis', 'Paraguay', 'République de Moldova', 'Cabo Verde', 'Érythrée', 'Mongolie', 'Uruguay', 'Saint-Marin', 'Djibouti', 'Ghana', 'République de Corée', 'République populaire démocratique de Corée', 'Malaisie', 'Jamaïque', 'République centrafricaine', 'Philippines', 'Bulgarie', 'Bahamas', 'Cameroun', 'Thaïlande', 'Gambie', 'Monaco', 'Chypre', 'Afghanistan', 'Liban', 'Guam', 'El Salvador', 'Panama', 'Brunéi Darussalam', 'Tchéquie', 'Géorgie', 'République démocratique du Timor-Leste', 'Gabon', 'Hong Kong, Chine', 'Afrique du Sud', 'Honduras', 'Équateur', 'Seychelles', 'Kosovo', 'Fidji', 'Burkina Faso', 'Zambie', 'Slovaquie', 'Comores', 'Guatemala', 'Papouasie-Nouvelle-Guinée', 'Pakistan', 'Îles Cook', 'Tunisie', 'Haïti', 'Croatie', 'Luxembourg', 'Tchad', 'Maurice', 'Lettonie', 'Congo', 'Sénégal', 'Îles Vierges britanniques', 'Mali', 'Guinée-Bissau', 'Andorre', 'Nicaragua', 'Bosnie-Herzégovine', 'Chinese Taipei', 'Malawi', 'Zimbabwe', 'Ouganda', 'Malte', 'Cambodge', 'Grenade', 'Îles Caïmans', 'Vanuatu', 'Népal', 'Îles Vierges américaines', 'Libéria', 'Tonga', 'Sao Tomé-et-Principe', 'Soudan du Sud', 'Estonie', 'République démocratique populaire lao', 'Suriname', 'Viet Nam', 'Mozambique', 'Bhoutan', 'Bénin', 'Costa Rica', 'Monténégro', 'Botswana', 'Macédoine du Nord', 'Aruba', 'Kiribati', 'Barbade', 'Madagascar', 'Îles Salomon', 'États fédérés de Micronésie', 'Palaos', 'Burundi', 'Bolivie', 'République-Unie de Tanzanie', 'Belize', 'Antigua-et-Barbuda', 'Saint-Vincent-et-les-Grenadines', 'Islande', 'Myanmar', 'Turkménistan', 'Somalie', 'Îles Marshall', 'Eswatini', 'Samoa américaines', 'Rwanda', 'Bangladesh', 'Namibie', 'Nauru', 'République démocratique du Congo', 'Sierra Leone', 'Dominique', 'Tuvalu', 'Lesotho', 'Liechtenstein']

In [6]:
unique_values_nb = df['Pays'].nunique()
print(unique_values_nb)

206

In [7]:
unique_values_list = df['Fonction'].unique().tolist()   
print(unique_values_list)

['Athlète', 'Athlète Remplaçant', 'Athlète remplaçant']